books/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "books"

urlpatterns = [
    path('', views.index, name="home")
]

greeting/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "greeting"

urlpatterns = [
    path('', views.index, name="home")
]

ppw-story-9/urls.py
from django.contrib import admin
from django.urls import path, include
from greeting import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', views.landing_page),
    path('greeting/', include('greeting.urls')),
    path('books/', include('books.urls')),
    path('profile/', include('profile.urls')),
]

profile/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "profile"

urlpatterns = [
    path('', views.index, name="home")
]

books/models.py
from django.db import models

greeting/models.py
from django.db import models
from django.contrib.auth.models import User
class User_info(models.Model):

	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
	status = models.TextField()
	profpic_link = models.CharField(max_length=100)

	def __unicode__(self):
		return self.user.username

profile/models.py
from django.db import models

books/forms.py
from django import forms

greeting/forms.py
from django import forms

profile/forms.py
from django import forms

books/views.py
from django.shortcuts import render, HttpResponse, redirect

def index(request):
	return render(request,"books/index.html")

greeting/views.py
from django.shortcuts import render, HttpResponse, redirect
from django import template
from django.template.defaultfilters import stringfilter

register = template.Library()

@register.filter
@stringfilter
def prepend(arg, prep):
	return prep + arg

def landing_page(request):
	return redirect('greeting:home')

def index(request):
	context = {'app' : 'greeting'}
	return render(request, 'greeting/index.html', context)

profile/views.py
from django.shortcuts import render, HttpResponse, redirect

def index(response):

	return render(response, 'profile/index.html')

books/templates/books/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Mencari Buku{% endblock %}

{% block custom_imports %}
    <link rel="stylesheet" href="{% static 'books/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'books/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'greeting/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'books/css/style.css' %}">

    <script src="{% static 'books/js/jquery.min.js' %}"></script>
    <script src="{% static 'books/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'books/js/bootstrap.min.js' %}"></script> 
    <script src="{% static 'books/js/my_js.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container mt-4">

      <div class="row justify-content-center">
        <div class="col">
         <h1 class="title">Mau baca apa hari ini?</h1>
        </div>
      </div>


      <input type="text" maxlength="200" class='form-control' id="books_search_form" >
      <br />
      <button class="btn-lg submit_button" id="books_search_button">Cari!</button>
      <br />
      <br />

    </div>

    <img src="{% static 'books/assets/loading2.gif' %}" id="loading_gif" class="mx-auto">

    <div class="container" id="books_results" style="background-color: #caa9e6; color:#2d283e;">

    </div>



    
    
{% endblock %}

profile/templates/profile/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block custom_imports %}
    <link rel="stylesheet" href="{% static 'profile/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'profile/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'greeting/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'profile/css/style.css' %}">

    <script src="{% static 'profile/js/jquery.min.js' %}"></script>
    <script src="{% static 'profile/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profile/js/bootstrap.min.js' %}"></script> 
    <script src="{% static 'profile/js/my_js.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="container mt-4">

     <div class="row">
      <div class="col-8"><h1>Halo, selamat datang!</h1></div>
      <div class="col-4"><button class="btn-lg" id="theme_switch_button">Change Theme!</button></div>

     </div>

    <br />
    <img src="{% static 'profile/assets/galang.jpg' %}" class="d-block img-fluid mb-3 mx-auto" style="max-width: 20em; max-height: 20em">
     <div class="row textbox accordion first_element" id="1">
        <div class="col">
 
          <h2>Aktivitasku</h2>
          <ul class="accordion-slide">
            <li><h3>Asdos DDP 1 2019/2020</h3></li>
            <li><h3>Menulis blog jurnalgalang.com</h3></li>
            <li><h3>Mencari duit dengan halal</h3></li>
            <li><h3>Menjadi orang baik :)</h3></li>
          </ul>

      </div>
     </div>
     <div class="row textbox accordion" id="2">
        <div class="col">

          <h2>Organisasi dan Kepanitiaan</h2>
          <ul class="accordion-slide">
            <li><h3>Scientific Committee Pelatnas TOKI 2019/2020</h3></li>
            <li><h3>Junior Member RISTEK DS 2019</h3></li>
            <li><h3>Staff BEM Keilmuan 2019</h3></li>
          </ul>

      </div>
     </div>

     <div class="row textbox accordion" id="3">
        <div class="col">

          <h2>Prestasi</h2>
          <ul class="accordion-slide">
            <li><h3>Yu-Gi-Oh! Duel Links Asia Regional Participant 2019</h3></li>
            <li><h3>Juara 2 lomba makan burger FIB 2018</h3></li>
            <li><h3>Terlucu PMB 2018</h3></li>
            <li><h3>Juara 1 lomba Cookierun Telkomsel Se-Bali 2015</h3></li>
          </ul>

      </div>
     </div>



    </div>
    
{% endblock %}

templates/base/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Bootstrap -->
    {% block custom_imports %}
    {% endblock %}
    

    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>

      <nav class="navbar navbar-expand-lg navbar-custom mb-4">
      <div class="container">

        <button class="navbar-toggler mr-3" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand mr-auto" href="#">GGO</a>

        <div class="d-flex flex-row order-2 order-lg-3">
         <div class="navbar-nav flex-row">
            {% if user.is_authenticated %}    
              <span class="navbar-text" id="username-header">
                {{ user.username }}
              </span>

             <!--  <a href="{% url 'logout' %}"><button class="btn" id="auth_button">Logout</button></a> -->
              <span class="navbar-btn ml-2" id="auth_button">
                  <a href="{% url 'logout' %}" class="btn">Logout</a>
    
          </span>
              <!-- <button  class="btn" id="auth_button"  onclick="goto_page({% url 'logout' %})">Logout</a> -->
            {% else %}
              <span class="navbar-text" id="username-header">
                pengunjung
              </span>

             <!--  <a href="{% url 'login' %}"><button class="btn" id="auth_button">Login</button></a> -->
              <span class="navbar-btn ml-2" id="auth_button">
                  <a href="{% url 'login' %}" class="btn">Login</a>
              </span>
              <!-- <button class="btn" id="auth_button" onclick="goto_page({% url 'login' %})" >Login</a> -->
            {% endif %}
            
          </div>

          

        
        </div> 
        <!-- Brand and toggle get grouped for better mobile display -->
        <!-- This is the actual code that creates the "hamburger icon" -->
        <!-- The data-target grabs ids to put into the icon -->
      
        <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
        <div class="collapse navbar-collapse order-3 order-lg-2" id="bs-example-navbar-collapse-1">
          <div class="navbar-nav">

            <a class="nav-item nav-link active" href="{% url 'greeting:home' %}">Beranda<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'profile:home' %}">Tentang Aku</a>
            <a class="nav-item nav-link" href="{% url 'books:home' %}">Cari Buku</a>

          </div>

        </div> <!-- /.navbar-collapse -->

        



      </div>
    </nav>
     {% block content %}

     {% endblock %}
  </body>
</html>

templates/greeting/index.html
{% extends "base/base.html" %}
{% load static %}

{% block custom_imports %}
<link rel="stylesheet" href="{% static 'greeting/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'greeting/css/bootstrap-grid.min.css' %}">
<link rel="stylesheet" href="{% static 'greeting/css/style.css' %}">

<script src="{% static 'greeting/js/jquery.min.js' %}"></script>
<script src="{% static 'greeting/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'greeting/js/bootstrap.min.js' %}"></script> 
<script src="{% static 'greeting/js/my_js.js' %}"></script>
{% endblock %}
{% block title %}Hi!{% endblock %}



{% block content %}
<div class="container">
  {% if user.is_authenticated %}
    <div class="row justify-content-center mb-3">
      <h1> Halo, {{ user.username }}! </h1>
    </div>
    
    <!-- <script>load_profile_picture( "{{ user.user_info.profpic_link }}" )</script>
    
    <div id="prof_loc">

    </div> -->
    <div class="row justify-content-center mb-3">
      <img class="img-fluid px-3" src={{ user.user_info.profpic_link }} alt="Tidak ada foto profil!">
    </div>

    <div class="row justify-content-center mb-3">
    <p> {{ user.user_info.status }}</p>
    </div>

  {% else %}
    <div class="row justify-content-center mb-3">
      <h1> Halo, pengunjung! </h1>
    </div>
    
    <div class="row justify-content-center mb-3">
     <p> Silahkan login terlebih dahulu :) </p>
    </div>
  {% endif %}
<div>
{% endblock %}